# Generated by Django 5.0.2 on 2024-03-01 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roast_date', models.DateField()),
                ('roast_level', models.CharField(max_length=50)),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
