# Generated by Django 5.0.2 on 2024-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('roast_level', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
