# Generated by Django 5.0.2 on 2024-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_coffeebean_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebean',
            name='roast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffeebean',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
