# Generated by Django 5.0.2 on 2024-02-26 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_coffeebean_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebean',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffeebean',
            name='roast_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
