# Generated by Django 5.0.2 on 2024-02-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_coffeebean_origin_alter_coffeebean_roast_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeebean',
            old_name='quantity',
            new_name='weight',
        ),
    ]
