# Generated by Django 5.0.2 on 2024-03-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='CustomPermission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
